### ISSUE TITLE
How do I make my own dataset

### ISSUE THREAD

**Issue by DYH200009** [zvict/papr#3]
In the dataset you gave for the tanksandtemples, how the individual files were made. I now have a video recorded by HD camera, how do I process his background and get his rgb/pose folder and bbox/intrinsics/test_traj.txt

**Comment by niopeng** [comment]
Hi, 

The tanks and temples dataset was provided by [Point-NeRF](https://github.com/Xharlie/pointnerf?tab=readme-ov-file#tanks--temples). To make your own dataset, we would recommend the following:
1. For getting the camera poses and intrinsics from video: you can use colmap and run this [script](https://github.com/NVlabs/instant-ngp/blob/master/docs/nerf_dataset_tips.md#colmap) provided by Instant-NGP.
2. To segment the main object from the background: you can use tools such as [SAM-Track](https://github.com/z-x-yang/Segment-and-Track-Anything), or photoshop.

Hope this helps!

**Comment by DYH200009** [comment]
Thank you,my bro
