### ISSUE TITLE
UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm

### ISSUE THREAD

**Issue by tristanengst** [zvict/papr#4]
As in the title. Thrown from `models.mlp.py`.

**Comment by zvict** [comment]
Thanks for the feedback! The issue is fixed in [commit ](https://github.com/zvict/papr/commit/24cebcf01ce08badc308abfdfa18e68d9fb636b2) with new environment requirements.
